First review
franclobo/Copy-Youtube-Reply pull request #1
Opened 2022-03-26 21:20 UTC by franclobo

###Review one of my past projects.

- Create a new empty repo "Copy-Youtube-Reply".
- Copy my code from the project that I completed during the Admissions Trial: "[Youtube-replica](https://github.com/franclobo/Youtube-replica)".
- Create a new branch for my copied code "First-review".
- Open a pull request.
- Add as many comments as possible in the given time and finish my review.
- Add a minimum of 2 comments.

2022-03-28 21:41 UTC, franclobo reviewed
### To Highlight 💯

No linters errors ✔️
Descriptive pull request ✔️
Descriptive commit messages ✔️

### Required Changes ♻️

Check the comments under the review.

Cheers and Happy coding!👏👏👏

2022-03-28 21:41 UTC, franclobo commented on README-Copy.md
> +This is an challenge where I have to do two things -- embedding the YouTube video player into the page so it actually plays and showing little thumbnail images along the right side.
- Please open this [Link](https://github.com/microverseinc/readme-template)
In the Link, what you find is the ReadMe Template that needs to be used.

Remember to customize this ReadMe Template to your project, the README file should be descriptive 👍

2022-03-28 21:41 UTC, franclobo commented on index.html
> +    <nav id="menuprincipal">
It is better to use the class attribute than the id attribute.

2022-03-28 21:41 UTC, franclobo commented on index.html
> +    </footer>
Kindly delete the code that you are not using.

2022-03-28 21:41 UTC, franclobo commented on styles.css
> +}
Kindly use the class attribute.

2022-03-28 21:41 UTC, franclobo reviewed
### To Highlight 💯

No linters errors ✔️
Descriptive pull request ✔️
Descriptive commit messages ✔️

### Required Changes ♻️

Check the comments under the review.

Cheers and Happy coding!👏👏👏

2022-03-28 22:01 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @franclobo,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![SoCloseKeeganMichaelKeyGIF](https://user-images.githubusercontent.com/50941074/160494426-2b325a20-8e4f-4def-a79d-50e595c0f339.gif)

## Highlights
✔️ Linters are working fine
✔️ Used GitHub inline comment feature well. 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-29 00:18 UTC, franclobo reviewed
To Highlight 💯
No linters errors ✔️
Descriptive pull request ✔️
Descriptive commit messages ✔️

Required Changes ♻️
Check the comments under the review.

Cheers and Happy coding!👏👏👏

2022-03-29 00:18 UTC, franclobo commented on index.html
> +    <nav id="menuprincipal">
I think it would be better to use the class attribute here instead of the id attribute because it is a good practice for coding in CSS. 👍

2022-03-29 00:18 UTC, franclobo commented on index.html
> +    </footer>
Kindly delete the tag that you are not using or empty to make your code clean.  Use the appropriate tags for each element (e.g., links, titles, etc.) and use HTML5 semantic tags (e.g., header, nav) over divs.🤝

2022-03-29 00:18 UTC, franclobo commented on styles.css
> +}
I think it would be better to use the class attribute here instead of the id attribute because it is a good practice for coding in CSS. 👍
You could check this article for more information: [Good and Bad CSS practices for begginers](https://speckyboy.com/good-bad-css-practices/)

2022-03-29 00:26 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @franclobo,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-29 00:55 UTC, merged